init:
    - git config --global core.autocrlf true

# Call on gradle to build and run tests
# --no-daemon: Prevent the daemon from launching to prevent file-in-use errors
#     when we cache the ~/.gradle directory

build_script:
    - gradlew.bat --no-daemon assemble

test_script:
    - gradlew.bat --no-daemon headless checkstyleMain checkstyleTest allTests

environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
        - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

# Files/folders to preserve between builds to speed them up
cache:
    - C:\Users\appveyor\.gradle

matrix:
    fast_finish: true  # Finish build once any job fails
