@startuml
start
:User executes command;
'New

if () then ([command commits AddressBook])
    :Purge redunant states;
    :Save AddressBook to
    addressBookStateList;
else ([else])
endif
stop
@enduml
