@startuml
!include style.puml

' TODO: Split diagram by package and supplement with description

skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR
skinparam packageStyle Rectangle
hide members
hide circle
package Logic {

package Parser {
Interface Parser <<Interface>>
Class AddressBookParser
Class XYZCommandParser
Class CliSyntax
Class ParserUtil
Class ArgumentMultimap
Class ArgumentTokenizer
Class Prefix
}

package Command {
Class XYZCommand
Abstract Class Command <<Abstract>>
}

Interface Logic <<Interface>>
Class LogicManager
Class CommandHistory
}

package Model{
Class HiddenModel #FFFFFF
hide circle
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .up.|> Logic
LogicManager -left->"1" CommandHistory
LogicManager -->"1" AddressBookParser
LogicManager -[hidden]->"1" AddressBookParser
AddressBookParser -left-> XYZCommandParser: creates >

XYZCommandParser ..> XYZCommand : creates >
XYZCommandParser ..|> Parser
XYZCommandParser ..> ArgumentTokenizer
XYZCommandParser ..> ArgumentMultimap
ArgumentTokenizer .right.> ArgumentMultimap
Parser -right[hidden]-> ArgumentTokenizer
XYZCommandParser ..> CliSyntax
XYZCommandParser ..> ParserUtil
ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix
XYZCommand .up.> Command
LogicManager ..> Command : executes >

LogicManager --> Model
Command .right.> Model
note right of XYZCommand: XYZCommand = AddCommand, \nFindCommand, etc
@enduml
