@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "list"

package States <<rectangle>> {
    class State1 as "__ab0:AddressBook__"
    class State2 as "__ab1:AddressBook__"
    class State3 as "__ab2:AddressBook__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State" #FFFFF

Pointer -up-> State2
@end
