@startuml
!include style.puml
skinparam ClassFontColor #000000
hide members
hide circle

package States {
    class State1 as "__ab0:AddressBook__"
    class State2 as "__ab1:AddressBook__"
    class State3 as "__ab2:AddressBook__"
}
State1 -[hidden]right-> State2
State2 -[hidden]right-> State3
hide State2
hide State3

class Pointer as "CurrentState = 0" #FFFFF
Pointer -up-> State1
@end

@startuml
!include style.puml
skinparam ClassFontColor #000000
hide members
hide circle


package States <<rectangle>> {
    class State1 as "__ab0:AddressBook__"
    class State2 as "__ab1:AddressBook__"
    class State3 as "__ab2:AddressBook__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

hide State3


class Pointer as "CurrentState = 1" #FFFFF

Pointer -up-> State2 : Delete Person
@end

@startuml
!include style.puml
skinparam ClassFontColor #000000
hide members
hide circle


package States <<rectangle>> {
    class State1 as "__ab0:AddressBook__"
    class State2 as "__ab1:AddressBook__"
    class State3 as "__ab2:AddressBook__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "CurrentState = 2" #FFFFF

Pointer -up-> State3 : add n/David

@end

@startuml
!include style.puml
skinparam ClassFontColor #000000
hide members
hide circle


package States <<rectangle>> {
    class State1 as "__ab0:AddressBook__"
    class State2 as "__ab1:AddressBook__"
    class State3 as "__ab2:AddressBook__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "CurrentState = 1" #FFFFF

Pointer -up-> State2 : undo

@end

@startuml
!include style.puml
skinparam ClassFontColor #000000
hide members
hide circle


package States <<rectangle>> {
    class State1 as "__ab0:AddressBook__"
    class State2 as "__ab1:AddressBook__"
    class State3 as "__ab2:AddressBook__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "CurrentState = 1" #FFFFF

Pointer -up-> State2 : list

@end

@startuml
!include style.puml
skinparam ClassFontColor #000000
hide members
hide circle


package States <<rectangle>> {
    class State1 as "__ab0:AddressBook__"
    class State2 as "__ab1:AddressBook__"
    class State3 as "__ab3:AddressBook__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "CurrentState = 2" #FFFFF

Pointer -up-> State3 : clear

note right on link: State ab2 deleted.
@end
