= Anas Shakra - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: TuitionConnect

---

== Overview

TuitionConnect is a Task-Management system designed for tutors. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 12 kLoC.

== Summary of contributions

* *Major enhancement*: Integrated *a new Task class into the application*
** What it does: The addressbook application is now able to interact, in various ways, with the newly created task object. In doing so, tutors are capable of generating and manipulating their various appointments at will. This enhancment inclues the ability to store the task object in the addressbook.
** Justification: This feature forms the foundation of the application as the app is based on a tutor's ability to create and interact with a task object in an addressbook environemnt.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to almost every aspect of the codebase.
** Credits: While no outside code was used, it was useful to look over how the Person class interacted with the addressbook and see how that can be adjusted to allow the pre-existing codebase to accomodate the Task object.

* *Minor enhancement*: added a listTask command that allows the user to view all tasks stored in the addressbook.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Wrote additional tests for existing features (Pull requests https://github.com[#68])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#68]
*** Updated Developer Guide to explain features: https://github.com[#68]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#128]


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[3.5]

include::../UserGuide.adoc[Command Summary]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=Task]

include::../DeveloperGuide.adoc[tag=listTask]