== PROJECT PLAN

*pass:[<u>CHRS v1.1</u>]:*

Lim Yi Sheng

    Program the filter function so that the program can display one specific field requested by the user.
    Edit the current help function

Chua Zhen Wei

    Program the modification for salary and bonus increment and decrement

Chen Qunming

    Devise and program relevant fields template for adding, updating and deleting of employees’ data

Vernon Cher Chu Xiong

    Devise and program the expenses field template for adding, viewing
    and removing of expenses incurred by specific employees

William Ng Zhi Hong

    Program leave/off approval or rejection function requested by each employee.
    Program work schedule for individual employees.
    Introduce primary and foreign key for employee ID to the other fields.



*pass:[<u>CHRS v1.2</u>]:*

Lim Yi Sheng

    Edit the filter function such that the program can display multiple fields as requested by the user
    Edit the filter function such that it is sorted based on a requested field
    Edit the search function such that it can search via other fields instead of by name only

Chua Zhen Wei

    Enhance the feature of salary and bonus increment/decrement to
    be for the whole organisation instead of just an individual

Chen Qunming

    Make all commands case insensitive
    Program a new function that resets the leave/off balance for the whole organisation

Vernon Cher Chu Xiong

    Enhance the view expenses feature to be for the whole organisation instead of just an individual

William Ng Zhi Hong

    Program work and leave schedule to show the manpower distribution of the organisation across the month



CHRS v1.3:

Lim Yi Sheng

    Integrate a mean of communication, such as email or chat messenger, so that the user can contact a specific employee if required

Chua Zhen Wei

    Program a display of the total percentage in pay increase since the day of employment for each employee

Chen Qunming

    Data encryption for all plaintext fields

Vernon Cher Chu Xiong

    Program a display of the history of the past expenses incurred by the company

William Ng Zhi Hong

    Generate a history report for each employee to show when each leave was consumed previously
    Integrate profile picture for each employee




